# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(201, 105, 92);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.browse_button.setFont(font)
        self.browse_button.setStyleSheet("background-color: rgb(230, 255, 250);")
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout.addWidget(self.browse_button)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("background-color: rgb(230, 255, 250);")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_6.addWidget(self.save_button)
        self.save_box = QtWidgets.QComboBox(self.centralwidget)
        self.save_box.setObjectName("save_box")
        self.save_box.addItem("")
        self.save_box.addItem("")
        self.save_box.addItem("")
        self.save_box.addItem("")
        self.horizontalLayout_6.addWidget(self.save_box)
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.axialGrid = QtWidgets.QGridLayout()
        self.axialGrid.setObjectName("axialGrid")
        self.axial_vSlider = QtWidgets.QSlider(self.centralwidget)
        self.axial_vSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axial_vSlider.sizePolicy().hasHeightForWidth())
        self.axial_vSlider.setSizePolicy(sizePolicy)
        self.axial_vSlider.setMinimumSize(QtCore.QSize(0, 1))
        self.axial_vSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.axial_vSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.axial_vSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.axial_vSlider.setMaximum(255)
        self.axial_vSlider.setPageStep(9)
        self.axial_vSlider.setProperty("value", 128)
        self.axial_vSlider.setSliderPosition(128)
        self.axial_vSlider.setTracking(True)
        self.axial_vSlider.setOrientation(QtCore.Qt.Vertical)
        self.axial_vSlider.setInvertedAppearance(True)
        self.axial_vSlider.setInvertedControls(False)
        self.axial_vSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.axial_vSlider.setTickInterval(1)
        self.axial_vSlider.setObjectName("axial_vSlider")
        self.axialGrid.addWidget(self.axial_vSlider, 1, 0, 1, 1)
        self.axialLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axialLabel.sizePolicy().hasHeightForWidth())
        self.axialLabel.setSizePolicy(sizePolicy)
        self.axialLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axialLabel.setObjectName("axialLabel")
        self.axialGrid.addWidget(self.axialLabel, 2, 1, 1, 1)
        self.axial_vBox = QtWidgets.QVBoxLayout()
        self.axial_vBox.setSpacing(9)
        self.axial_vBox.setObjectName("axial_vBox")
        self.axial_hBox = QtWidgets.QHBoxLayout()
        self.axial_hBox.setObjectName("axial_hBox")
        self.window1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.window1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.window1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.window1.setObjectName("window1")
        self.axial_hBox.addWidget(self.window1)
        self.axial_vBox.addLayout(self.axial_hBox)
        self.axialGrid.addLayout(self.axial_vBox, 1, 1, 1, 1)
        self.axial_hSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axial_hSlider.sizePolicy().hasHeightForWidth())
        self.axial_hSlider.setSizePolicy(sizePolicy)
        self.axial_hSlider.setMinimumSize(QtCore.QSize(1, 0))
        self.axial_hSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.axial_hSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.axial_hSlider.setStyleSheet("")
        self.axial_hSlider.setMaximum(255)
        self.axial_hSlider.setProperty("value", 128)
        self.axial_hSlider.setTracking(True)
        self.axial_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.axial_hSlider.setInvertedAppearance(False)
        self.axial_hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.axial_hSlider.setTickInterval(1)
        self.axial_hSlider.setObjectName("axial_hSlider")
        self.axialGrid.addWidget(self.axial_hSlider, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.axialGrid)
        self.coronalGrid = QtWidgets.QGridLayout()
        self.coronalGrid.setObjectName("coronalGrid")
        self.coronal_vSlider = QtWidgets.QSlider(self.centralwidget)
        self.coronal_vSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coronal_vSlider.sizePolicy().hasHeightForWidth())
        self.coronal_vSlider.setSizePolicy(sizePolicy)
        self.coronal_vSlider.setMinimumSize(QtCore.QSize(0, 1))
        self.coronal_vSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.coronal_vSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.coronal_vSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.coronal_vSlider.setMaximum(255)
        self.coronal_vSlider.setPageStep(9)
        self.coronal_vSlider.setProperty("value", 128)
        self.coronal_vSlider.setSliderPosition(128)
        self.coronal_vSlider.setTracking(True)
        self.coronal_vSlider.setOrientation(QtCore.Qt.Vertical)
        self.coronal_vSlider.setInvertedAppearance(True)
        self.coronal_vSlider.setInvertedControls(False)
        self.coronal_vSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.coronal_vSlider.setTickInterval(1)
        self.coronal_vSlider.setObjectName("coronal_vSlider")
        self.coronalGrid.addWidget(self.coronal_vSlider, 1, 0, 1, 1)
        self.coronal_vBox = QtWidgets.QVBoxLayout()
        self.coronal_vBox.setObjectName("coronal_vBox")
        self.coronal_hBox = QtWidgets.QHBoxLayout()
        self.coronal_hBox.setObjectName("coronal_hBox")
        self.window2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.window2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.window2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.window2.setObjectName("window2")
        self.coronal_hBox.addWidget(self.window2)
        self.coronal_vBox.addLayout(self.coronal_hBox)
        self.coronalGrid.addLayout(self.coronal_vBox, 1, 1, 1, 1)
        self.coronalLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coronalLabel.sizePolicy().hasHeightForWidth())
        self.coronalLabel.setSizePolicy(sizePolicy)
        self.coronalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coronalLabel.setObjectName("coronalLabel")
        self.coronalGrid.addWidget(self.coronalLabel, 2, 1, 1, 1)
        self.coronal_hSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coronal_hSlider.sizePolicy().hasHeightForWidth())
        self.coronal_hSlider.setSizePolicy(sizePolicy)
        self.coronal_hSlider.setMinimumSize(QtCore.QSize(1, 0))
        self.coronal_hSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.coronal_hSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.coronal_hSlider.setStyleSheet("")
        self.coronal_hSlider.setMaximum(255)
        self.coronal_hSlider.setProperty("value", 128)
        self.coronal_hSlider.setTracking(True)
        self.coronal_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.coronal_hSlider.setInvertedAppearance(False)
        self.coronal_hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.coronal_hSlider.setTickInterval(1)
        self.coronal_hSlider.setObjectName("coronal_hSlider")
        self.coronalGrid.addWidget(self.coronal_hSlider, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.coronalGrid)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saggitalGrid = QtWidgets.QGridLayout()
        self.saggitalGrid.setObjectName("saggitalGrid")
        self.sagittal_vSlider = QtWidgets.QSlider(self.centralwidget)
        self.sagittal_vSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sagittal_vSlider.sizePolicy().hasHeightForWidth())
        self.sagittal_vSlider.setSizePolicy(sizePolicy)
        self.sagittal_vSlider.setMinimumSize(QtCore.QSize(0, 1))
        self.sagittal_vSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.sagittal_vSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sagittal_vSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sagittal_vSlider.setMaximum(255)
        self.sagittal_vSlider.setPageStep(9)
        self.sagittal_vSlider.setProperty("value", 128)
        self.sagittal_vSlider.setSliderPosition(128)
        self.sagittal_vSlider.setTracking(True)
        self.sagittal_vSlider.setOrientation(QtCore.Qt.Vertical)
        self.sagittal_vSlider.setInvertedAppearance(True)
        self.sagittal_vSlider.setInvertedControls(False)
        self.sagittal_vSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sagittal_vSlider.setTickInterval(1)
        self.sagittal_vSlider.setObjectName("sagittal_vSlider")
        self.saggitalGrid.addWidget(self.sagittal_vSlider, 1, 0, 1, 1)
        self.saggital_vBox = QtWidgets.QVBoxLayout()
        self.saggital_vBox.setObjectName("saggital_vBox")
        self.saggital_hBox = QtWidgets.QHBoxLayout()
        self.saggital_hBox.setObjectName("saggital_hBox")
        self.window3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.window3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.window3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.window3.setObjectName("window3")
        self.saggital_hBox.addWidget(self.window3)
        self.saggital_vBox.addLayout(self.saggital_hBox)
        self.saggitalGrid.addLayout(self.saggital_vBox, 1, 1, 1, 1)
        self.sagittal_hSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sagittal_hSlider.sizePolicy().hasHeightForWidth())
        self.sagittal_hSlider.setSizePolicy(sizePolicy)
        self.sagittal_hSlider.setMinimumSize(QtCore.QSize(1, 0))
        self.sagittal_hSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.sagittal_hSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sagittal_hSlider.setStyleSheet("")
        self.sagittal_hSlider.setMaximum(255)
        self.sagittal_hSlider.setProperty("value", 128)
        self.sagittal_hSlider.setTracking(True)
        self.sagittal_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sagittal_hSlider.setInvertedAppearance(False)
        self.sagittal_hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sagittal_hSlider.setTickInterval(1)
        self.sagittal_hSlider.setObjectName("sagittal_hSlider")
        self.saggitalGrid.addWidget(self.sagittal_hSlider, 0, 1, 1, 1)
        self.sagittalLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sagittalLabel.sizePolicy().hasHeightForWidth())
        self.sagittalLabel.setSizePolicy(sizePolicy)
        self.sagittalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sagittalLabel.setObjectName("sagittalLabel")
        self.saggitalGrid.addWidget(self.sagittalLabel, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.saggitalGrid)
        self.mprGrid = QtWidgets.QGridLayout()
        self.mprGrid.setObjectName("mprGrid")
        self.mpr_hSlider = QtWidgets.QSlider(self.centralwidget)
        self.mpr_hSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpr_hSlider.sizePolicy().hasHeightForWidth())
        self.mpr_hSlider.setSizePolicy(sizePolicy)
        self.mpr_hSlider.setMinimumSize(QtCore.QSize(0, 1))
        self.mpr_hSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.mpr_hSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mpr_hSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mpr_hSlider.setMaximum(255)
        self.mpr_hSlider.setPageStep(9)
        self.mpr_hSlider.setProperty("value", 128)
        self.mpr_hSlider.setSliderPosition(128)
        self.mpr_hSlider.setTracking(True)
        self.mpr_hSlider.setOrientation(QtCore.Qt.Vertical)
        self.mpr_hSlider.setInvertedAppearance(True)
        self.mpr_hSlider.setInvertedControls(False)
        self.mpr_hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mpr_hSlider.setTickInterval(1)
        self.mpr_hSlider.setObjectName("mpr_hSlider")
        self.mprGrid.addWidget(self.mpr_hSlider, 2, 0, 1, 1)
        self.mprLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mprLabel.sizePolicy().hasHeightForWidth())
        self.mprLabel.setSizePolicy(sizePolicy)
        self.mprLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mprLabel.setObjectName("mprLabel")
        self.mprGrid.addWidget(self.mprLabel, 4, 1, 1, 1)
        self.mpr_vBox = QtWidgets.QVBoxLayout()
        self.mpr_vBox.setObjectName("mpr_vBox")
        self.mpr_hBox = QtWidgets.QHBoxLayout()
        self.mpr_hBox.setObjectName("mpr_hBox")
        self.window4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.window4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.window4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.window4.setObjectName("window4")
        self.mpr_hBox.addWidget(self.window4)
        self.mpr_vBox.addLayout(self.mpr_hBox)
        self.mprGrid.addLayout(self.mpr_vBox, 2, 1, 1, 1)
        self.generate_button = QtWidgets.QPushButton(self.centralwidget)
        self.generate_button.setObjectName("generate_button")
        self.mprGrid.addWidget(self.generate_button, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.angle_mpr = QtWidgets.QLineEdit(self.centralwidget)
        self.angle_mpr.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.angle_mpr.setMaxLength(4)
        self.angle_mpr.setFrame(True)
        self.angle_mpr.setAlignment(QtCore.Qt.AlignCenter)
        self.angle_mpr.setObjectName("angle_mpr")
        self.horizontalLayout_4.addWidget(self.angle_mpr)
        self.planes_box = QtWidgets.QComboBox(self.centralwidget)
        self.planes_box.setObjectName("planes_box")
        self.planes_box.addItem("")
        self.planes_box.addItem("")
        self.planes_box.addItem("")
        self.horizontalLayout_4.addWidget(self.planes_box)
        self.mprGrid.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.mprGrid)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.axial_hSlider.valueChanged['int'].connect(self.coronal_hSlider.setValue)
        self.coronal_hSlider.valueChanged['int'].connect(self.axial_hSlider.setValue)
        self.axial_vSlider.valueChanged['int'].connect(self.sagittal_hSlider.setValue)
        self.sagittal_hSlider.valueChanged['int'].connect(self.axial_vSlider.setValue)
        self.sagittal_vSlider.valueChanged['int'].connect(self.coronal_vSlider.setValue)
        self.coronal_vSlider.valueChanged['int'].connect(self.sagittal_vSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Imaging Modalities Final Project"))
        self.label_5.setText(_translate("MainWindow", "Multi Planner Reconstruction"))
        self.browse_button.setText(_translate("MainWindow", "Open"))
        self.save_button.setText(_translate("MainWindow", "Save Slice"))
        self.save_box.setItemText(0, _translate("MainWindow", "Axial"))
        self.save_box.setItemText(1, _translate("MainWindow", "Coronal"))
        self.save_box.setItemText(2, _translate("MainWindow", "Sagittal"))
        self.save_box.setItemText(3, _translate("MainWindow", "MPR"))
        self.axialLabel.setText(_translate("MainWindow", "Axial (Transpose)"))
        self.coronalLabel.setText(_translate("MainWindow", "Coronal"))
        self.sagittalLabel.setText(_translate("MainWindow", "Sagittal"))
        self.mprLabel.setText(_translate("MainWindow", "MPR"))
        self.generate_button.setText(_translate("MainWindow", "Generate"))
        self.label.setText(_translate("MainWindow", "Angle:"))
        self.angle_mpr.setText(_translate("MainWindow", "45"))
        self.planes_box.setItemText(0, _translate("MainWindow", "Axial"))
        self.planes_box.setItemText(1, _translate("MainWindow", "Coronal"))
        self.planes_box.setItemText(2, _translate("MainWindow", "Sagittal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

